# Libraries we need
require "validatable"
require "validatable-validates_list_items_in_list"
require "couchrest"
require "couchrest_extended_document"

require "macrodeck-platform/monkeypatches"
require "macrodeck-platform/couchrest_search"
require "macrodeck-platform/introspection"
require "macrodeck-platform/turk_support"
require "macrodeck-platform/model"
require "macrodeck-platform/data_object_definition"
require "macrodeck-platform/data_object"
require "macrodeck-platform/platform"
require "macrodeck-platform/platform_data_objects"
require "macrodeck-platform/geospatial_object"
require "macrodeck-platform/turk_task"
require "macrodeck-platform/pathable_hash"
